GestionsNotes/GestionsNotes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
  
]

GestionsNotes/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [ 
    path("login/", views.login, name="login"),
    path("", views.index, name="dashboard"),
    path("etudiant/", views.etudiant, name="liste-etudient"),
    path("modifier/<int:id>/", views.modifEtidiant, name="modifier"),
    path("supprimer/<int:id>/", views.suppEtidiant, name="supprimer"),
    path("note/", views.note, name="note"),

  
]

GestionsNotes/dashboard/models.py
from django.db import models

# Create your models here.


from django import forms
# Create your models here.

class Classe(models.Model):
    id = models.AutoField(primary_key=True)
    nom_classe = models.CharField( max_length=100)
    niveau_classe = models.CharField( max_length=100)

    def __str__(self):
        return self.nom_classe

class Module(models.Model):
    id = models.AutoField(primary_key=True)
    nom_module = models.CharField( max_length=100)
    coiffi_module = models.CharField( max_length=100)
    classe= models.ForeignKey(Classe,  on_delete=models.CASCADE)
    

    def __str__(self):
        return self.nom_module 



class Matiere(models.Model):
    id = models.AutoField(primary_key=True)
    nom_matiere = models.CharField( max_length=100)
    coiffi_matiere = models.CharField( max_length=100)
    #note_devoir = models.CharField( max_length=100)
    #note_exemen = models.CharField( max_length=100)
    module= models.ForeignKey(Module,  on_delete=models.CASCADE)
    

    def __str__(self):
        return self.nom_matiere 


class Etudiant(models.Model):
    sex_etudiant = [
        ('M','M'),
        ('F','F'),
    ]

    id = models.AutoField(primary_key=True)
    nom_etudiant = models.CharField( max_length=100)
    prenom_etudiant = models.CharField( max_length=100)
    matricule_etudiant = models.CharField( max_length=100)
    cin_etudiant = models.CharField( max_length=50)
    date_nai_etudiant = models.DateField('Date Naissance')
    adresse_etudiant = models.CharField( max_length=100)
    tel_etudiant = models.CharField( max_length=100)
    #id_resultat_etudiant  = models.ForeignKey( max_length=50)
    classe = models.ForeignKey(Classe,  on_delete=models.CASCADE)
    sex = models.CharField( max_length=50, choices=sex_etudiant)
    def __str__(self):
        return self.nom_etudiant


class Resultat(models.Model):
    id = models.AutoField(primary_key=True)
    moyen_general = models.FloatField(default=0)
    etudiant= models.ForeignKey(Etudiant,on_delete=models.CASCADE)

class Specialite(models.Model):
    id = models.AutoField(primary_key=True)
    nom_specialite = models.CharField( max_length=100)
    classe= models.ForeignKey(Classe,  on_delete=models.CASCADE)
    

    def __str__(self):
        return self.nom_specialite    

class Note(models.Model):
    id = models.AutoField(primary_key=True)
    Note_devoir = models.FloatField(default=0)
    Note_examen = models.FloatField(default=0)
    etudiant= models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    matiere= models.ForeignKey(Matiere,on_delete=models.CASCADE)
       


#class resultat(models.Model):
#    id_resultat= models.CharField( max_length=100)
#    moyn = models.CharField( max_length=100)


#    def __str__(self):
#        return self.moyn

   
 

GestionsNotes/dashboard/forms.py
from django import forms
from .models import Etudiant,Note

class EtudiantForms(forms.ModelForm):
    class Meta :
        model = Etudiant
        fields = '__all__'
        widgets = {
            'nom_etudiant' :forms.TextInput(attrs={'class' : 'form-control'}),
            'prenom_etudiant' :forms.TextInput(attrs={'class' : 'form-control'}),
            'matricule_etudiant' :forms.TextInput(attrs={'class' : 'form-control'}),
            'cin_etudiant' :forms.TextInput(attrs={'class' : 'form-control'}),
            'date_nai_etudiant' :forms.TextInput(attrs={'class' : 'form-control'}),
            'adresse_etudiant' :forms.TextInput(attrs={'class' : 'form-control'}),
            'tel_etudiant' :forms.TextInput(attrs={'class' : 'form-control'}),
            'classe' :forms.Select(attrs={'class' : 'form-control'}),
            'sex' :forms.Select(attrs={'class' : 'form-control'})
        }
class NoteForms(forms.ModelForm):
    class Meta :
        model = Note
        fields = ['Note_devoir','Note_examen','etudiant','matiere']
        widgets = {
            'Note_devoir' :forms.TextInput(attrs={'class' : 'form-control'}),
            'Note_examen' :forms.TextInput(attrs={'class' : 'form-control'}),
            'etudiant' :forms.Select(attrs={'class' : 'form-control'}),
            'matiere' :forms.Select(attrs={'class' : 'form-control'}),           
        }

GestionsNotes/dashboard/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from .models import *
from .forms import NoteForms,EtudiantForms
from django.http import JsonResponse
from django.core import serializers
# Create your views here.



#def pivot_data(request):
#    dataset = Etudiant.objects.all()
#    data = serializers.serialize('json', dataset)
#    return JsonResponse(data, safe=False)

def login(request):
    return render(request, 'dashboard/authentication-login.html')


def index(request):
    return render(request, 'dashboard/index.html')

def note(request):
    context ={
       # 'notes' : Note.objects.all(),
        'forms' : NoteForms(),
    }
    return render(request, 'dashboard/note.html',context)




def modifEtidiant(request,id):
    etudiant_id = Etudiant.objects.get(id=id)
    if request.method =='POST':
        etudiant_save = EtudiantForms(request.POST,request.FILES,instance=etudiant_id)
        if etudiant_save.is_valid():
            etudiant_save.save()
            return redirect('/etudiant')
    else:
        etudiant_save = EtudiantForms(instance=etudiant_id)
        context = {
            'forms':etudiant_save,
        }
    return render(request, "dashboard/modifierEtudiant.html",context)


def suppEtidiant(request,id):
    etudiant_supp = Etudiant.objects.get(id=id)
    if request.method =='POST':
        etudiant_supp.delete()
        return redirect('/')
    return render(request,"dashboard/suprimerEtudiant.html")

def etudiant(request):
    if request.method == 'POST':
        ajout_etudiant = EtudiantForms(request.POST)
        if ajout_etudiant.is_valid():
            ajout_etudiant.save()
    context ={
        'etudiants' : Etudiant.objects.all(),
        'form' : EtudiantForms(),
    }
    return render(request, "dashboard/etudiant.html", context)





def elements(request):
    return render(request, "dashboard/elements.html")

GestionsNotes/templates/base.html
{% load static %}

{% block html %}
<!DOCTYPE html>
<html lang="en">
{% block head %}
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
  
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/Capture.png' %}">
    <title>Gestions des Notes</title>
                <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/animation.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/asColorPicker.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/fullcalendar.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/calendar.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/responsive.bootstrap4.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.gritter.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.minicolors.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.steps.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/materialdesignicons.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/multicheck.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/perfect-scrollbar.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/quill.core.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/quill.snow.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/select2.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/steps.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/themify-icons.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/toastr.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/float-chart.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/style.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/custom.css' %}" rel="stylesheet"/>
    <!-- HTML5 Shim and Respond.js' %} IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js' %} doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js' %}/1.4.2/respond.min.js' %}"></script>
<![endif]-->
   {% block extra_style %}{% endblock extra_style %}
</head>
{% endblock head %}
   
   {% block body %}
   
       <body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css' %} -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
         {% include 'dashboard/includes/header.html' %}
         {% include 'dashboard/includes/sidebar.html' %}
          <div class="page-wrapper">
           {% block content %}{% endblock content %}
           {% include 'dashboard/includes/footer.html' %}
         </div>
    </div>

    {% block script %}
    
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}"></script>
        <script src="{% static 'js/sparkline.js' %}"></script>
        <script src="{% static 'js/waves.js' %}"></script>
        <script src="{% static 'js/sidebarmenu.js' %}"></script>
        <script src="{% static 'js/custom.min.js' %}"></script>

        <script src="{% static 'js/excanvas.js' %}"></script>
        <script src="{% static 'js/jquery.flot.js' %}"></script>
        <script src="{% static 'js/jquery.flot.pie.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.stack.js' %}"></script>
        <script src="{% static 'js/jquery.flot.crosshair.js' %}"></script>
        <script src="{% static 'js/jquery.flot.tooltip.min.js' %}"></script>
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/chart-page-init.js' %}"></script>
        <script src="{% static 'js/app-style-switcher.js' %}"></script>
        <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'js/datatable-checkbox-init.js' %}"></script>
        <script src="{% static 'js/datatables.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'js/responsive.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/jquery.charts-sparkline.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/jquery-asColor.min.js' %}"></script>
        <script src="{% static 'js/jquery-asGradient.js' %}"></script>
        <script src="{% static 'js/jquery-asColorPicker.min.js' %}"></script>
        <script src="{% static 'js/jquery.minicolors.min.js' %}"></script>
        <script src="{% static 'js/jquery.multicheck.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/toastr.min.js' %}"></script>
        <script src="{% static 'js/select2.full.min.js' %}"></script>
        <script src="{% static 'js/select2.min.js' %}"></script>
        <script src="{% static 'js/jquery.inputmask.bundle.min.js' %}"></script>
        <script src="{% static 'js/quill.min.js' %}"></script>
        <script src="{% static 'js/mask.init.js' %}"></script>
        <script src="{% static 'js/meg.init.js' %}"></script>
        <script src="{% static 'js/cal-init.js' %}"></script>
        <script src="{% static 'constant/strings.js' %}"></script>
        <script src="{% static 'constant/validator.js' %}"></script>

        <script>
            $(document).ready(function () {
                $('#example').DataTable();
            });
        </script>
        <script>
            $(document).ready(function () {
                $('#zero_config').DataTable();
            });
        </script>
        


    {% block extra_script %}{% endblock extra_script %}

    
    {% endblock script %}

    </body>
   {% endblock body %}


{% endblock html %}

GestionsNotes/templates/dashboard/etudiant.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
{% endblock %}
{% block page_title %}
 Form
{% endblock %}
{% block content %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Listes des etudiants</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Library</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row m-1 mb-3">
                        <a href="#etudiantForms" class="btn btn-primary" data-toggle="collapse">Ajout +</a>
                    </div>
                    <div id="etudiantForms" class="card card-primary collapse">
                        <div class="card-header">
                            <h3  class="card-title">Ajout</h3>
                        </div>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="card-body">
                                {{ form }}
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Ajout</button>
                            </div>
                        </form>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered">
                            <thead class="table-primary">
                            <tr align="center">
                                <th>Nom</th>
                                <th>Prenom</th>
                                <th>Matricule</th>
                                <th>CIN</th>
                                <th>Date Naissance</th>
                                <th>Adresse</th>
                                <th>Telephone</th>
                                <th>Sex</th>
                                <th>Modifier</th>
                                <th>Supprimer</th>
                            </tr>
                            </thead>
                            <tbody>
                                
                            {% for etudiant  in etudiants  %}
                                    
                            <tr align="center">
                                <td>{{ etudiant.nom_etudiant }}</td>
                                <td>{{ etudiant.prenom_etudiant }}</td>
                                <td>{{ etudiant.matricule_etudiant }}</td>
                                <td>{{ etudiant.cin_etudiant }}</td>
                                <td>{{ etudiant.date_nai_etudiant }}</td>
                                <td>{{ etudiant.adresse_etudiant }}</td>
                                <td>{{ etudiant.tel_etudiant }}</td>
                                <td>{{ etudiant.sex }}</td>
                                    
                                <td>
                                    <a href="{% url 'dashboard:modifier' etudiant.id %}"><i class="far fa-edit"></i></a>
                                </td>
                                <td>
                                    <a href="{% url 'dashboard:supprimer' etudiant.id %}"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr align="center">
                                <th>Nom</th>
                                <th>Prenom</th>
                                <th>Matricule</th>
                                <th>CIN</th>
                                <th>Date Naissance</th>
                                <th>Adresse</th>
                                <th>Telephone</th>
                                <th>Sex</th>
                                <th>Modifier</th>
                                <th>Supprimer</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

{% block extra_js %}
           <script>
            //***********************************//
            // For select 2
            //***********************************//
            $(".select2").select2();

            /*colorpicker*/
            $('.demo').each(function () {
                //
                // Dear reader, it's actually very easy to initialize MiniColors. For example:
                //
                //  $(selector).minicolors();
                //
                // The way I've done it below is just for the demo, so don't get confused
                // by it. Also, data- attributes aren't supported at this time...they're
                // only used for this demo.
                //
                $(this).minicolors({
                    control: $(this).attr('data-control') || 'hue',
                    position: $(this).attr('data-position') || 'bottom left',

                    change: function (value, opacity) {
                        if (!value) return;
                        if (opacity) value += ', ' + opacity;
                        if (typeof console === 'object') {
                            console.log(value);
                        }
                    },
                    theme: 'bootstrap'
                });

            });
            /*datwpicker*/
            jQuery('.mydatepicker').datepicker();
            jQuery('#datepicker-autoclose').datepicker({
                autoclose: true,
                todayHighlight: true
            });

            var quill = new Quill('#editor', {
                theme: 'snow'
            });
        </script>
{% endblock %}

GestionsNotes/templates/dashboard/includes/footer.html
{% load static %}
  <footer class="footer text-center">
    Tous droits réservés par Gestions Des Notes<a href="https://Gestions.com"></a>.
            </footer>

GestionsNotes/templates/dashboard/includes/header.html
{% load static %}
<style>

      .header{
          background-color: blue;
      }
</style>
 <header class="topbar" data-navbarbg="skin5">
            <nav id="navbar" class="navbar fixed-top top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <!-- This is for the sidebar toggle which is visible on mobile only -->
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i>
                    <!-- ============================================================== -->
                    <!-- Logo -->
                    <!-- ============================================================== -->
                   <!-- <a class="navbar-brand" href="/../index.html">
                         Logo icon -->
                        <b class="logo-icon p-l-10">
                           
                            <!--<img src="{% static 'images/logo-icon.png' %}" alt="homepage" class="img-circle" />-->
                           
                        </b>
                        <!--End Logo icon -->
                         <!-- Logo text -->
                        <span class="logo-text">
                             <!-- dark Logo text 
                             <img src="{% static 'images/logo-text.png' %}" alt="homepage" class="light-logo" />-->
                            
                        </span>
                        <!-- Logo icon -->
                        <!-- <b class="logo-icon"> -->
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <!-- <img src="{% static 'images/logo-text.png' %}" alt="homepage" class="light-logo" /> -->
                            
                        <!-- </b> -->
                        <!--End Logo icon -->
                    </a>
                    <!-- ============================================================== -->
                    <!-- End Logo -->
                    <!-- ============================================================== -->
                    <!-- ============================================================== -->
                    <!-- Toggle which is visible on mobile only -->
                    <!-- ============================================================== -->
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                        <!-- ============================================================== -->
                        <!-- create new -->

                        <!-- Search -->
                        <!-- ============================================================== -->
                        <li class="nav-item search-box"> <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <form class="app-search position-absolute">
                                <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                            </form>
                        </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- Right side toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav float-right">
                        <!-- ============================================================== -->
                       
                    
                        <!-- ============================================================== -->
                        <!-- User profile and search -->
                        <!-- ============================================================== -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{% static 'images/users/1.jpg' %}" alt="user" class="rounded-circle" width="31"></a>
                            <div class="dropdown-menu dropdown-menu-right user-dd animated">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="javascript:void(0)"><i class="ti-settings m-r-5 m-l-5"></i> Account Setting</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'dashboard:login' %}"><i class="fa fa-power-off m-r-5 m-l-5"></i> Déconnecter</a>
                                <div class="dropdown-divider"></div>
                                <div class="p-l-30 p-10"><a href="javascript:void(0)" class="btn btn-sm btn-success btn-rounded">View Profile</a></div>
                            </div>
                        </li>
                        <!-- ============================================================== -->
                        <!-- User profile and search -->
                        <!-- ============================================================== -->
                    </ul>
                </div>
            </nav>
        </header>

GestionsNotes/templates/dashboard/includes/sidebar.html
{% load static %}

  <aside class="left-sidebar scrollable ps-container ps-theme-default ps-active-y" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-graduation-cap"></i><span class="hide-menu">Les studiant </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">

                                <li class="sidebar-item"><a href="{% url 'dashboard:liste-etudient' %}" class="sidebar-link"><i class="fas fa-list-ol"></i><span>Liste etudiants </span></a></li>
                                <li class="sidebar-item"><a href="{% url 'dashboard:note' %}" class="sidebar-link"><i class="fas fa-poll-h"></i><span class="hide-menu"> Les notes</span></a></li>
                            </ul>
                        </li>
                      <!--  <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-poll-h"></i><span class="hide-menu">Les Notes </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href="{% url 'dashboard:note' %}" class="sidebar-link"><i class="fas fa-poll-h"></i><span class="hide-menu"> Les notes</span></a></li>
                            </ul>
                        </li>-->
                        
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>